#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 19 12:25:58 2019

@author: srikanth
"""

import csv

with open('data1.csv') as csv_file:
    csv_reader = csv.reader(csv_file)
  
    for row in csv_reader:
        print(row)