#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 11 11:17:00 2019

@author: srikanth
"""

d={1:"murali",2:"siva",3:"bunny"}
for key,values in d.items():
    print(key,values)
print(d.values())
print(d.keys())