#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 21 16:33:25 2018

@author: srikanth
"""

import numpy as np
arr=np.arange(1,26).reshape(5,5)
print(arr)
print(arr.sum())
print(arr.std())
print(arr.sum(axis=1))