#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 11 11:43:07 2019

@author: srikanth
"""

l=[1,2,3,1,2,3,1,2,3,4,5]
count=0
s=set(l)
print(s)

for i in s:
    count=0
    for j in l:
        if(j==i):
            count+=1
    print(str(i)+" repeates  "+str(count)+" times")
        

    