#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 21 12:18:48 2019

@author: srikanth
"""

import numpy as np
l1=[1,2,3,4,5]
print(l1)
arr=np.array(l1)
print(arr)
l2=[[1,2,3],[4,5,6],[7,8,9]]
print(l2)
arr2=np.array(l2)
print(arr2)
arr3=np.arange(0,10)
print(arr3)
arr4=np.zeros(3)
print(arr4)
arr5=np.zeros((2,2))
print(arr5)
arr6=np.eye(4)
print(arr6)
arr7=np.linspace(0,5,10)
print(arr7)
arr8=np.random.rand(5)
print(arr8)
arr9=np.random.randint(1,100)
print(arr9)
arr10=np.random.randn(5)
print(arr10)
arr11=np.random.randint(1,100,10)
print(arr11)
print(arr11.reshape(2,5))
print(arr11.max())
print(arr11.min())
print(arr11.argmax())
print(arr11.argmin())
print(arr11)
print(arr11.dtype)

print(arr11.shape)

print("indexing  and selection")

arr12=np.arange(0,11)
print(arr12)
print(arr12[1:5])
arr12[1:3]=20
print(arr12)
arr13=arr12.copy()
print(arr13)
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(arr2d[0][2])
print(arr2d[1,2])
print(arr2d[0:2,1:])
print("conditonal selection")
bool_arr=arr12>5
print(bool_arr)
print(arr12[bool_arr])
print(arr12+arr13)
print(arr12*arr13)
print(arr12)
print(arr12+100)
print(arr12.sum())
print(arr12.std())

print(arr2d)
print(arr2d.sum(axis=0))
print(arr2d.sum(axis=1))









