#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 21 15:17:53 2019

@author: srikanth
"""

import pandas as pd
import numpy as np

ser1=pd.Series([1,2,3],['a','b','c'])
print(ser1)

from numpy.random import randn
np.random.seed(101)
arr=randn(5,4)
print(arr)

print(np.arange(0,20).reshape(5,4))
data=np.arange(0,20).reshape(5,4)
rows=['A','B','C','D','E']
cols=['W','X','Y','Z']
df=pd.DataFrame(data,rows,cols)
print(df)
"""

print(df.W)
print(df[['W','Z']])
df['new']=df['W']+df['Z']
df.drop('new',axis=1,inplace=True)
print(df)
df.drop('E',axis=0,inplace=True)
print(df.shape)
print(df.loc['A'])
print(df.iloc[2])
print(df.loc['A','Y'])
print(df)

print(df[df>4])
print(df[df['W']>4]['X'])




print("missing DATA")
d={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
print(d)
df=pd.DataFrame(d)
print(df)
print(df.dropna(axis=1))
print(df.dropna(thresh=2))
print(df.fillna(value="mk"))
print(df['A'].fillna(value=df['A'].mean()))
print(df.isnull)

print("groupby")
print(df.head)
df.to_csv('output.csv',index=False)
df1=pd.read_csv('output.csv')
print(df1)

"""
