#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 11 11:59:03 2019

@author: srikanth
"""

l=[1,2,3,1,2,3,4,5]
s=set(l)
count=0
for i in l:
    #print(i)
    if(i==1):
        count+=1
print(1+count)
