#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 24 15:34:06 2018

@author: srikanth
"""
# This Script displays the recent 5 posts of a user in Twitter

import twitter

usrname = input("Enter Twitter User Id or Short Name to display recent 5 tweets : ")

api = twitter.Api()

tweets = api.GetUserTimeline(usrname)

for i in range(5) :
    print("\nTweet(%d) - %s",i+1, tweets[i].text)
